### YamlMime:ManagedReference
items:
- uid: FareCalculator.Configuration.GeographyOptions
  commentId: T:FareCalculator.Configuration.GeographyOptions
  id: GeographyOptions
  parent: FareCalculator.Configuration
  children:
  - FareCalculator.Configuration.GeographyOptions.EarthRadiusKilometers
  - FareCalculator.Configuration.GeographyOptions.SectionName
  langs:
  - csharp
  - vb
  name: GeographyOptions
  nameWithType: GeographyOptions
  fullName: FareCalculator.Configuration.GeographyOptions
  type: Class
  source:
    remote:
      path: src/FareCalculator/Configuration/FareCalculationConfig.cs
      branch: fare-calculator
      repo: https://github.com/todicn/FareCalculator.git
    id: GeographyOptions
    path: src/FareCalculator/Configuration/FareCalculationConfig.cs
    startLine: 198
  assemblies:
  - FareCalculator
  namespace: FareCalculator.Configuration
  summary: Configuration options for geographical calculations.
  example: []
  syntax:
    content: public class GeographyOptions
    content.vb: Public Class GeographyOptions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: FareCalculator.Configuration.GeographyOptions.SectionName
  commentId: F:FareCalculator.Configuration.GeographyOptions.SectionName
  id: SectionName
  parent: FareCalculator.Configuration.GeographyOptions
  langs:
  - csharp
  - vb
  name: SectionName
  nameWithType: GeographyOptions.SectionName
  fullName: FareCalculator.Configuration.GeographyOptions.SectionName
  type: Field
  source:
    remote:
      path: src/FareCalculator/Configuration/FareCalculationConfig.cs
      branch: fare-calculator
      repo: https://github.com/todicn/FareCalculator.git
    id: SectionName
    path: src/FareCalculator/Configuration/FareCalculationConfig.cs
    startLine: 203
  assemblies:
  - FareCalculator
  namespace: FareCalculator.Configuration
  summary: Configuration section name in appsettings.json.
  example: []
  syntax:
    content: public const string SectionName = "Geography"
    return:
      type: System.String
    content.vb: Public Const SectionName As String = "Geography"
- uid: FareCalculator.Configuration.GeographyOptions.EarthRadiusKilometers
  commentId: P:FareCalculator.Configuration.GeographyOptions.EarthRadiusKilometers
  id: EarthRadiusKilometers
  parent: FareCalculator.Configuration.GeographyOptions
  langs:
  - csharp
  - vb
  name: EarthRadiusKilometers
  nameWithType: GeographyOptions.EarthRadiusKilometers
  fullName: FareCalculator.Configuration.GeographyOptions.EarthRadiusKilometers
  type: Property
  source:
    remote:
      path: src/FareCalculator/Configuration/FareCalculationConfig.cs
      branch: fare-calculator
      repo: https://github.com/todicn/FareCalculator.git
    id: EarthRadiusKilometers
    path: src/FareCalculator/Configuration/FareCalculationConfig.cs
    startLine: 208
  assemblies:
  - FareCalculator
  namespace: FareCalculator.Configuration
  summary: Gets or sets the Earth's radius in kilometers for distance calculations.
  example: []
  syntax:
    content: public double EarthRadiusKilometers { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property EarthRadiusKilometers As Double
  overload: FareCalculator.Configuration.GeographyOptions.EarthRadiusKilometers*
references:
- uid: FareCalculator.Configuration
  commentId: N:FareCalculator.Configuration
  href: FareCalculator.html
  name: FareCalculator.Configuration
  nameWithType: FareCalculator.Configuration
  fullName: FareCalculator.Configuration
  spec.csharp:
  - uid: FareCalculator
    name: FareCalculator
    href: FareCalculator.html
  - name: .
  - uid: FareCalculator.Configuration
    name: Configuration
    href: FareCalculator.Configuration.html
  spec.vb:
  - uid: FareCalculator
    name: FareCalculator
    href: FareCalculator.html
  - name: .
  - uid: FareCalculator.Configuration
    name: Configuration
    href: FareCalculator.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: FareCalculator.Configuration.GeographyOptions.EarthRadiusKilometers*
  commentId: Overload:FareCalculator.Configuration.GeographyOptions.EarthRadiusKilometers
  href: FareCalculator.Configuration.GeographyOptions.html#FareCalculator_Configuration_GeographyOptions_EarthRadiusKilometers
  name: EarthRadiusKilometers
  nameWithType: GeographyOptions.EarthRadiusKilometers
  fullName: FareCalculator.Configuration.GeographyOptions.EarthRadiusKilometers
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double
  nameWithType: double
  fullName: double
  nameWithType.vb: Double
  fullName.vb: Double
  name.vb: Double
