### YamlMime:ManagedReference
items:
- uid: FareCalculator.Configuration.DistanceBasedFareOptions
  commentId: T:FareCalculator.Configuration.DistanceBasedFareOptions
  id: DistanceBasedFareOptions
  parent: FareCalculator.Configuration
  children:
  - FareCalculator.Configuration.DistanceBasedFareOptions.BaseFare
  - FareCalculator.Configuration.DistanceBasedFareOptions.PerKilometerRate
  langs:
  - csharp
  - vb
  name: DistanceBasedFareOptions
  nameWithType: DistanceBasedFareOptions
  fullName: FareCalculator.Configuration.DistanceBasedFareOptions
  type: Class
  source:
    remote:
      path: src/FareCalculator/Configuration/FareCalculationConfig.cs
      branch: fare-calculator
      repo: https://github.com/todicn/FareCalculator.git
    id: DistanceBasedFareOptions
    path: src/FareCalculator/Configuration/FareCalculationConfig.cs
    startLine: 83
  assemblies:
  - FareCalculator
  namespace: FareCalculator.Configuration
  summary: Configuration options for distance-based fare calculation.
  example: []
  syntax:
    content: public class DistanceBasedFareOptions
    content.vb: Public Class DistanceBasedFareOptions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: FareCalculator.Configuration.DistanceBasedFareOptions.BaseFare
  commentId: P:FareCalculator.Configuration.DistanceBasedFareOptions.BaseFare
  id: BaseFare
  parent: FareCalculator.Configuration.DistanceBasedFareOptions
  langs:
  - csharp
  - vb
  name: BaseFare
  nameWithType: DistanceBasedFareOptions.BaseFare
  fullName: FareCalculator.Configuration.DistanceBasedFareOptions.BaseFare
  type: Property
  source:
    remote:
      path: src/FareCalculator/Configuration/FareCalculationConfig.cs
      branch: fare-calculator
      repo: https://github.com/todicn/FareCalculator.git
    id: BaseFare
    path: src/FareCalculator/Configuration/FareCalculationConfig.cs
    startLine: 88
  assemblies:
  - FareCalculator
  namespace: FareCalculator.Configuration
  summary: Gets or sets the base fare amount before distance calculation.
  example: []
  syntax:
    content: public decimal BaseFare { get; set; }
    parameters: []
    return:
      type: System.Decimal
    content.vb: Public Property BaseFare As Decimal
  overload: FareCalculator.Configuration.DistanceBasedFareOptions.BaseFare*
- uid: FareCalculator.Configuration.DistanceBasedFareOptions.PerKilometerRate
  commentId: P:FareCalculator.Configuration.DistanceBasedFareOptions.PerKilometerRate
  id: PerKilometerRate
  parent: FareCalculator.Configuration.DistanceBasedFareOptions
  langs:
  - csharp
  - vb
  name: PerKilometerRate
  nameWithType: DistanceBasedFareOptions.PerKilometerRate
  fullName: FareCalculator.Configuration.DistanceBasedFareOptions.PerKilometerRate
  type: Property
  source:
    remote:
      path: src/FareCalculator/Configuration/FareCalculationConfig.cs
      branch: fare-calculator
      repo: https://github.com/todicn/FareCalculator.git
    id: PerKilometerRate
    path: src/FareCalculator/Configuration/FareCalculationConfig.cs
    startLine: 93
  assemblies:
  - FareCalculator
  namespace: FareCalculator.Configuration
  summary: Gets or sets the rate per kilometer.
  example: []
  syntax:
    content: public decimal PerKilometerRate { get; set; }
    parameters: []
    return:
      type: System.Decimal
    content.vb: Public Property PerKilometerRate As Decimal
  overload: FareCalculator.Configuration.DistanceBasedFareOptions.PerKilometerRate*
references:
- uid: FareCalculator.Configuration
  commentId: N:FareCalculator.Configuration
  href: FareCalculator.html
  name: FareCalculator.Configuration
  nameWithType: FareCalculator.Configuration
  fullName: FareCalculator.Configuration
  spec.csharp:
  - uid: FareCalculator
    name: FareCalculator
    href: FareCalculator.html
  - name: .
  - uid: FareCalculator.Configuration
    name: Configuration
    href: FareCalculator.Configuration.html
  spec.vb:
  - uid: FareCalculator
    name: FareCalculator
    href: FareCalculator.html
  - name: .
  - uid: FareCalculator.Configuration
    name: Configuration
    href: FareCalculator.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: FareCalculator.Configuration.DistanceBasedFareOptions.BaseFare*
  commentId: Overload:FareCalculator.Configuration.DistanceBasedFareOptions.BaseFare
  href: FareCalculator.Configuration.DistanceBasedFareOptions.html#FareCalculator_Configuration_DistanceBasedFareOptions_BaseFare
  name: BaseFare
  nameWithType: DistanceBasedFareOptions.BaseFare
  fullName: FareCalculator.Configuration.DistanceBasedFareOptions.BaseFare
- uid: System.Decimal
  commentId: T:System.Decimal
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.decimal
  name: decimal
  nameWithType: decimal
  fullName: decimal
  nameWithType.vb: Decimal
  fullName.vb: Decimal
  name.vb: Decimal
- uid: FareCalculator.Configuration.DistanceBasedFareOptions.PerKilometerRate*
  commentId: Overload:FareCalculator.Configuration.DistanceBasedFareOptions.PerKilometerRate
  href: FareCalculator.Configuration.DistanceBasedFareOptions.html#FareCalculator_Configuration_DistanceBasedFareOptions_PerKilometerRate
  name: PerKilometerRate
  nameWithType: DistanceBasedFareOptions.PerKilometerRate
  fullName: FareCalculator.Configuration.DistanceBasedFareOptions.PerKilometerRate
